function geo = convert_estimate_scattering(geo)

% convert estimate(..) to explicit scattering values using catt formula s =
% 50·sqrt(d/λ), where d is the given value in meter and λthe wavelength.
%
% geoOut = convert_estimate_scattering(geoIn)
% 
% geo is a structure as that generated by the read_geo function.
% 

% init locals
sound_speed = 343; % m/s
freqs = [125 250 500 1000 2000 4000 8000 16000];

% loop over materials
for iMat = 1:length(geo.materials)
    
    % init locals
    material = geo.materials(iMat);
    nBands = length(material.absorption);

    % discard if no estimate
    if( isnan(material.estimate) ); continue; end

    % convert to explicit values
    material.scattering = 50*sqrt(material.estimate * freqs / sound_speed);

    % clamp 
    material.scattering = max(material.scattering, 0);
    material.scattering = min(material.scattering, 99);

    % truncate freq bands to match number defined for absorption
    material.scattering = material.scattering(1:nBands);
    
    % update estimate value to indicate change 
    material.estimate = NaN;

    % save to locals
    geo.materials(iMat) = material;

end
