function [md9] = md9_enable_receivers(md9, ids)

% enable a list of receivers in md9 
%
% [md9] = md9_enable_receivers(md9, ids)
%
%
% md9 is a structure as that generated by the read_md9 function.
% ids is an array of ints in [0,99]

% sanity check 
if( min(ids) < 0 || max(ids) > 99 ); error('receiver ids should be in [0,99]'); end

% set active receivers
md9.receivers_used(ids+1) = 1;