function [md9] = md9_enable_sources(md9, ids)

% enable a list of sources in md9 
%
% [md9] = md9_enable_sources(md9, ids)
%
%
% md9 is a structure as that generated by the read_md9 function.
% ids is an array of ints in [0,260] or a cell of strings like 
% {'A0', 'A7', 'B1', ...};

% source format is {'A0', 'A7', 'B1', ...}
if( iscellstr(ids) )
    
    % init locals
    idsNum = [];

    % convert id string to id numerical
    sourceLetters = {'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'};
    for iSource = 1:length(ids)

        % init locals
        idStr = ids{iSource};

        % letter to number
        id1 = find( ismember(sourceLetters, idStr(1)) );
        if( isempty(id1) ); error('unexpected source id: %s', idStr); end

        % subnumber extract
        id2 = str2double(idStr(2));

        % reconstruct id numerical
        idsNum(end+1) = (id1-1) * 10 + id2;
    end

    % save to locals
    ids = idsNum;

end
    
% sanity check 
if( min(ids) < 0 || max(ids) > 259 ); error('source ids should be in [0,259]'); end

% to line
tmp = md9.sources_used.';
srcUsed = tmp(:);

% set values
srcUsed(ids+1) = 1;

% to matrix
srcUsed = reshape(srcUsed, 10, 26);
md9.sources_used = srcUsed.';
