function [] = write_receiver(filepath, rcv)

% write_receiver write receiver data to a .loc catt file
% 
% [] = write_receiver(filepath, rcv)
%
% filepath is a string.
% rcv is a structure as that generated by the read_receiver function

% open file
fid = fopen(filepath, 'w');

% file header
fprintf(fid, ';File automatically generated from Matlab script\r\n');
fprintf(fid, 'RECEIVERS\r\n');
fprintf(fid, '\r\n');

% loop over receivers
for iRcv = 1:length(rcv)
    
    % init locals
    r = rcv(iRcv);

    % shape line
    line = sprintf('%s %.2f %.2f %.2f', r.idStr, r.xyz);
    if( ~all(isnan(r.aimpos)) )
        line = [line sprintf('%.2f %.2f %.2f', r.aimpos)];
    end
    line = [line '\r\n'];
    
    % write to file
    fprintf(fid, line);
        
end

% close file
fclose(fid);

end